# https://hub.docker.com/_/mongo
version: "3.1"

services:
  mongo-db:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - my-mongo-db:/etc/mongo
    ports:
      - "27017:27017"
volumes:
  my-mongo-db:
# docker exec -it mysql-db bash
# mysql -p
# use nodejs;
